version: '3.8'
services:
  caddy:
    image: roam-notes
    container_name: caddy
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./caddy_data:/data
      - ./caddy_config:/config
      - ./public_html:/public_html
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
